# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c714ec1649fe2ce96914f3a8db8e1f84a01622192589ad30dab72d2cfa035e51847ce29bdf921e310bb9e0e481e8d232edbe772d1b96fe6b3b53f4716c9d1b71

test:
  secret_key_base: d7cc0588c0e5a42ef4fa6805bd760faf4bb3742759f85eaf60513be30bb2c07d429f7fa6d878b70bd3331dfef126ba6fdc7f3a29ec88bef2aecdfd72dd8d6532

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

<h1>Text Form</h1>

<% if user.type == "Student" %>
<%=form_tag("/students/#{user[:id]}/texty", method: "post") do %>
  <%= label_tag "Phone Number"%>
  <%=text_field_tag :phone_num , @user.phone%>
  <%=label_tag "Message"%>
  <%=text_area_tag :body, @user.first_name + ", You have reach a total of " +@danger_student_ids.to_s+ " absences please contact your producer as soon as possible"%>
  <%=submit_tag "Send Text"%>
<%end%>