# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create([{id: 1, name: "Jason Booras", email: "jasonbooras@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 2, name: "Dana Gill", email: "d.gill.design@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 3, name: "Ismail Jaafari", email: "ismailj@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 4, name: "Sara Abbasi", email: "saraa@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 5, name: "Zachary Boyd", email: "zacharyb@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 6, name: "Jason Chan", email: "jasonc@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 7, name: "Peter Cirincione", email: "peterc@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 8, name: "Fatima Faloye", email: "fatimaf@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 9, name: "Leonel Delamo Jr.", email: "leoneld@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 10, name: "Diana Frank", email: "dianaf@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 11, name: "Ruth Acosta", email: "rutha@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 12, name: "Eric Boateng", email: "ericb@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 13, name: "Josue Cardona", email: "josuec@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 14, name: "Jeselin Castillo", email: "jeselinc@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 15, name: "Louis Di Meglio", email: "louisd@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 16, name: "Brandon Goldenberg", email: "brandong@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 17, name: "Shawn Hanna", email: "shawnh@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 18, name: "Michael L. Clair", email: "michaell@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 19, name: "Dan Lynn", email: "danl@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 20, name: "Chris Mahr", email: "chrism@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 21, name: "Esther Mohadeb", email: "estherm@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 22, name: "Jared Murphy", email: "jaredm@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 23, name: "Danielle Nourok", email: "daniellen@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 24, name: "Angela Perez", email: "angelap@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 25, name: "Nicolai Robles", email: "nicolair@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 26, name: "Rita Luczak", email: "luczak@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 27, name: "Leeanne Gillett", email: "gillett@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 28, name: "Luvenia Walkup", email: "walkup@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 29, name: "Cathern Funke", email: "funke@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 30, name: "Georgeanna Betancourt", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 31, name: "January Krieg", email: "krieg@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 32, name: "Dell Fairclough", email: "fairclough@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 33, name: "Analisa Sholtis", email: "sholtis@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 34, name: "Donetta Nolf", email: "nolf@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 35, name: "Gisela Youngberg", email: "youngberg@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 36, name: "Aundrea Bressler", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 37, name: "Carmine Wight", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 38, name: "Weldon Tope", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 39, name: "Yan Weatherly", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 40, name: "Kellye Keefer", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 41, name: "Tifany Holte", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 42, name: "Albert Utecht", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 43, name: "Shane Acree", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 44, name: "Kaylene Schrick", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 45, name: "Eleonor Montesinos", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 46, name: "Monty Overman", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 47, name: "Deena Escamilla", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 48, name: "Lavonna Peer", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 49, name: "Thi Livsey", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 50, name: "Gemma Caulder", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 51, name: "Jeneva Stoudemire", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 52, name: "Robin Ammons", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 53, name: "Santa Cosgrove", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 54, name: "Joleen Wilford", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 55, name: "Elida Hebb", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 56, name: "Arron Stalls", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 57, name: "Violeta Radigan", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 58, name: "Katina Achenbach", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 59, name: "Morris Abdul", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 60, name: "Della Behrens", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 61, name: "Tuyet Tibbetts", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 62, name: "Priscila Nordby", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 63, name: "Lula Cazares", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 64, name: "Iona Lambeth", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 65, name: "Alica Mccrystal", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 66, name: "Ardella Conklin", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 67, name: "Caitlin Bostic", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 68, name: "Gretchen Zanchez", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 69, name: "Maris Cary", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 70, name: "Thuy Neidig", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 71, name: "Porter Letellier", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 72, name: "Ezra Proffit", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 73, name: "Numbers Dong", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 74, name: "Thomas Worrell", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 75, name: "Candance Camarena", email: "fakename@gmail.com", password: "123", phone: "2121234567", type: "Student"},
             {id: 76, name: "John Bell", email: "jaredm@gmail.com", password: "123", phone: "2121234567", type: "Instructor"},
             {id: 77, name: "Jaden Carver", email: "jadenc@gmail.com", password: "123", phone: "2121234567", type: "Instructor"},
             {id: 78, name: "Dennis Liaw", email: "dennisl@gmail.com", password: "123", phone: "2121234567", type: "Instructor"},
             {id: 79, name: "Bryan Mytko", email: "bryanm@gmail.com", password: "123", phone: "2121234567", type: "Instructor"},
             {id: 80, name: "Bobby King", email: "bobbyk@gmail.com", password: "123", phone: "2121234567", type: "Instructor"},
             {id: 81, name: "Ethan Barhydt", email: "ethanb@gmail.com", password: "123", phone: "2121234567", type: "Producer"}
             ])


Course.create([{id: 1, name: "Blue Steel"},
               {id: 2, name: "Magnum"},
               {id: 3, name: "Rubber Duck"},
               {id: 4, name: "Night's Watch"},
               {id: 5, name: "Burrito"}
              ])


CourseUser.create([{id: 1, user_id: 1, course_id: 1},
                   {id: 2, user_id: 2, course_id: 1},
                   {id: 3, user_id: 3, course_id: 1},
                   {id: 4, user_id: 4, course_id: 1},
                   {id: 5, user_id: 5, course_id: 1},
                   {id: 6, user_id: 6, course_id: 1},
                   {id: 7, user_id: 7, course_id: 1},
                   {id: 8, user_id: 8, course_id: 1},
                   {id: 9, user_id: 9, course_id: 2},
                   {id: 10, user_id: 10, course_id: 2},
                   {id: 11, user_id: 11, course_id: 2},
                   {id: 12, user_id: 12, course_id: 2},
                   {id: 13, user_id: 13, course_id: 2},
                   {id: 14, user_id: 14, course_id: 2},
                   {id: 15, user_id: 15, course_id: 2},
                   {id: 16, user_id: 16, course_id: 2},
                   {id: 17, user_id: 17, course_id: 2},
                   {id: 18, user_id: 18, course_id: 2},
                   {id: 19, user_id: 19, course_id: 2},
                   {id: 20, user_id: 20, course_id: 2},
                   {id: 21, user_id: 21, course_id: 2},
                   {id: 22, user_id: 22, course_id: 2},
                   {id: 23, user_id: 23, course_id: 2},
                   {id: 24, user_id: 24, course_id: 2},
                   {id: 25, user_id: 25, course_id: 2},
                   {id: 26, user_id: 26, course_id: 3},
                   {id: 27, user_id: 27, course_id: 3},
                   {id: 28, user_id: 28, course_id: 3},
                   {id: 29, user_id: 29, course_id: 3},
                   {id: 30, user_id: 30, course_id: 3},
                   {id: 31, user_id: 31, course_id: 3},
                   {id: 32, user_id: 32, course_id: 3},
                   {id: 33, user_id: 33, course_id: 3},
                   {id: 34, user_id: 34, course_id: 3},
                   {id: 35, user_id: 35, course_id: 3},
                   {id: 36, user_id: 36, course_id: 3},
                   {id: 37, user_id: 37, course_id: 3},
                   {id: 38, user_id: 38, course_id: 3},
                   {id: 39, user_id: 39, course_id: 3},
                   {id: 40, user_id: 40, course_id: 4},
                   {id: 41, user_id: 41, course_id: 4},
                   {id: 42, user_id: 42, course_id: 4},
                   {id: 43, user_id: 43, course_id: 4},
                   {id: 44, user_id: 44, course_id: 4},
                   {id: 45, user_id: 45, course_id: 4},
                   {id: 46, user_id: 46, course_id: 4},
                   {id: 47, user_id: 47, course_id: 4},
                   {id: 48, user_id: 48, course_id: 4},
                   {id: 49, user_id: 49, course_id: 4},
                   {id: 50, user_id: 50, course_id: 5},
                   {id: 51, user_id: 51, course_id: 5},
                   {id: 52, user_id: 52, course_id: 5},
                   {id: 53, user_id: 53, course_id: 5},
                   {id: 54, user_id: 54, course_id: 5},
                   {id: 55, user_id: 55, course_id: 5},
                   {id: 56, user_id: 56, course_id: 5},
                   {id: 57, user_id: 57, course_id: 5},
                   {id: 58, user_id: 58, course_id: 5},
                   {id: 59, user_id: 59, course_id: 5},
                   {id: 60, user_id: 60, course_id: 5},
                   {id: 61, user_id: 61, course_id: 5},
                   {id: 62, user_id: 62, course_id: 5},
                   {id: 63, user_id: 63, course_id: 5},
                   {id: 64, user_id: 64, course_id: 5},
                   {id: 65, user_id: 65, course_id: 5},
                   {id: 66, user_id: 66, course_id: 5},
                   {id: 67, user_id: 67, course_id: 5},
                   {id: 68, user_id: 68, course_id: 5},
                   {id: 69, user_id: 69, course_id: 5},
                   {id: 70, user_id: 70, course_id: 5},
                   {id: 71, user_id: 71, course_id: 5},
                   {id: 72, user_id: 72, course_id: 5},
                   {id: 73, user_id: 73, course_id: 5},
                   {id: 74, user_id: 74, course_id: 5},
                   {id: 75, user_id: 75, course_id: 5},
                   {id: 76, user_id: 26, course_id: 1},
                   {id: 77, user_id: 27, course_id: 2},
                   {id: 78, user_id: 28, course_id: 3},
                   {id: 79, user_id: 29, course_id: 4},
                   {id: 80, user_id: 30, course_id: 5}
                  ])


Attendance.create([{id: 1, danger: true, status: "late", date: 38.days.ago, user_id: 1, course_id: 1},
                   {id: 2, danger: false, status: "late", date: 37.days.ago, user_id: 1, course_id: 1},
                   {id: 3, danger: false, status: "late", date: 36.days.ago, user_id: 1, course_id: 1},
                   {id: 4, danger: false, status: "unexcused", date: 35.days.ago, user_id: 1, course_id: 1},
                   {id: 5, danger: false, status: "unexcused", date: 34.days.ago, user_id: 1, course_id: 1},
                   {id: 6, danger: false, status: "late", date: 38.days.ago, user_id: 2, course_id: 1},
                   {id: 7, danger: false, status: "late", date: 37.days.ago, user_id: 2, course_id: 1},
                   {id: 8, danger: false, status: "late", date: 36.days.ago, user_id: 2, course_id: 1},
                   {id: 9, danger: false, status: "late", date: 35.days.ago, user_id: 2, course_id: 1},
                   {id: 10, danger: false, status: "late", date: 34.days.ago, user_id: 2, course_id: 1},
                   {id: 11, danger: false, status: "late", date: 38.days.ago, user_id: 7, course_id: 2},
                   {id: 12, danger: false,  status: "late", date: 37.days.ago, user_id: 7, course_id: 2},
                   {id: 13, danger: false, status: "excused", date: 38.days.ago, user_id: 8, course_id: 2},
                   {id: 14, danger: true, status: "unexcused", date: 37.days.ago, user_id: 20, course_id: 5},
                   {id: 15, danger: false, status: "unexcused", date: 36.days.ago, user_id: 20, course_id: 5},
                   {id: 16, danger: false, status: "unexcused", date: 35.days.ago, user_id: 20, course_id: 5},
                   {id: 17, danger: false, status: "excused", date: 34.days.ago, user_id: 20, course_id: 5},
                   {id: 18, danger: false, status: "late", date: 38.days.ago, user_id: 13, course_id: 3},
                   {id: 19, danger: false, status: "late", date: 37.days.ago, user_id: 13, course_id: 3},
                   {id: 20, danger: false, status: "late", date: 36.days.ago, user_id: 13, course_id: 3},
                   {id: 21, danger: false, status: "excused", date: 38.days.ago, user_id: 16, course_id: 4},
                   {id: 22, danger: false, status: "unexcused", date: 37.days.ago, user_id: 17, course_id: 4},
                   {id: 23, danger: false, status: "unexcused", date: 36.days.ago, user_id: 18, course_id: 4},
                   {id: 24, danger: false, status: "late", date: 35.days.ago, user_id: 19, course_id: 4}
                  ])
